services:
  booking-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MSGPACK_PUREPYTHON=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  booking-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - booking-backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://booking-backend:8000
    command: npm run dev

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
