# Generated by Django 5.0.2 on 2024-02-10 02:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_first_name', models.CharField(max_length=100)),
                ('booker_last_name', models.CharField(max_length=100)),
                ('booker_email', models.CharField(max_length=200)),
                ('booker_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('denied', 'Denied')], default='pending', max_length=10)),
            ],
        ),
    ]
